import "dotenv/config"

export const ENV = {
    PORT : process.env.PORT,
    NODE_ENV: process.env.NODE_ENV,
    MONGO_URI: process.env.MONGO_URI,
    JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
    JWT_ACCESS_TOKEN_EXPIRE: process.env.JWT_ACCESS_TOKEN_EXPIRE,
    JWT_REFRESH_TOKEN_SECRET: process.env.JWT_REFRESH_TOKEN_SECRET,
    JWT_REFRESH_TOKEN_EXPIRE: process.env.JWT_REFRESH_TOKEN_EXPIRE,
    JWT_REFRESH_TOKEN_EXPIRE_REMEMBER_ME: process.env.JWT_REFRESH_TOKEN_EXPIRE_REMEMBER_ME,
    CLIENT_URL: process.env.CLIENT_URL
}